[versions]
# libraries
junit = "5.10.0"
spek = "2.0.19"
# language
java = "11"
kotlin = "1.8.22"

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "3.3.2" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }
license = { id = "com.jaredsburrows.license", version = "0.9.3" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
spek-junit = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
spek-jvm = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
findbugs = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.15" }
spockcore = { module = "org.spockframework:spock-core", version = "2.2-M1-groovy-3.0" } # 2.2-M3-groovy-4.0
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
