[versions]
junit = "6.0.1"
kotlin = "2.2.21"
spek = "2.0.19"

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.5" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
license = { id = "com.jaredsburrows.license", version = "0.9.8" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }

[libraries]
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "4.2.6" }
findbugs = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.2" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
spek-junit = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
spek-jvm = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
spockcore = { module = "org.spockframework:spock-core", version = "2.4-M6-groovy-4.0" }
